name: djangoflow_websocket
description: Easily manage connecting to a WebSocket server, subscribing to messages, handling reconnections etc all at once with djangoflow_websocket
version: 0.1.0+6
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_websocket

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.2
  djangoflow_bloc_extensions: ^0.0.2+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
