name: djangoflow_websocket
description: Easily manage connecting to a WebSocket server, subscribing to messages, handling reconnections etc all at once with djangoflow_websocket
version: 0.2.0
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_websocket

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  djangoflow_bloc_extensions: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
