name: djangoflow_analytics
description: A library for tracking analytics with multiple Analytics providers in Flutter applications.
version: 0.0.2+2
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  analytics: ^1.0.2
  flutter:
    sdk: flutter

  mockito: ^5.3.2

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
