name: djangoflow_local_notification
description: A streamlined and flexible local notification solution for Flutter mobile apps, seamlessly integrated with DjangoFlow framework to enable dynamic notification actions.
version: 0.0.2+9
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_local_notification

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  collection: ^1.18.0
  dio: ^5.5.0+1
  djangoflow_bloc_extensions: ^0.0.2+3
  djangoflow_openapi: ^0.1.22
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^17.2.1+2
  freezed_annotation: ^2.4.4
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.9.0
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
