name: djangoflow_local_notification
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.2
  collection: ^1.17.1
  dio: ^5.3.2
  djangoflow_openapi: ^0.0.16
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^15.1.0+1
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^9.1.2
  json_annotation: ^4.8.1
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
