name: djangoflow_auth_facebook
description: djangoflow_auth_facebook adds a touch of Facebook magic to your Flutter app with Djangoflow API
version: 0.1.0+6
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_auth/djangoflow_auth_facebook

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  djangoflow_auth: ^0.5.0+1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.3

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
