name: djangoflow_app
description: A simple, opinionated, and minimal Flutter application structure for quick start and easy maintenance.
version: 6.0.1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_app

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.1
  path_provider: ^2.1.5
  provider: ^6.1.2

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
