name: djangoflow_app
description: A simple, opinionated, and minimal Flutter application structure for quick start and easy maintenance.
version: 3.7.2
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  hydrated_bloc: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
