name: djangoflow_app
description: A simple, opinionated, and minimal Flutter application structure for quick start and easy maintenance.
version: 4.0.0
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_app

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^9.1.2
  json_annotation: ^4.8.1
  package_info_plus: ^6.0.0
  path_provider: ^2.1.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
