name: djangoflow_auth
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.2
  collection: ^1.17.1
  dio: ^5.2.1+1
  djangoflow_openapi: ^0.0.15
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.1
  freezed_annotation: ^2.2.0
  google_sign_in: ^6.1.4
  hydrated_bloc: ^9.1.2
  oauth2_client: ^3.2.1
  sign_in_with_apple: ^5.0.0
  universal_html: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0

dependency_overrides:
  # Due to oauth2_client does not support http: ^1.0.0
  # Can be removed one https://github.com/teranetsrl/oauth2_client/pull/168 merged
  http: ^1.0.0

flutter:
