name: djangoflow_auth
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.2
  collection: ^1.17.1
  dio: ^5.2.1+1
  djangoflow_openapi: ^0.0.14
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
