name: df_auth
description: Djangoflow authentication.
version: 0.0.1
homepage: https://github.com/djangoflow/flutter-djangoflow/packages/df_auth

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hydrated_bloc: ^8.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0

  openapi:
    path: ../openapi

flutter:
