name: djangoflow_remote_config
description: Djangoflow Remote Config is a library that helps to handle remote config in your flutter application.
version: 0.0.4+5
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_remote_config

environment:
  sdk: ">=3.1.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.3
  djangoflow_bloc_extensions: ^0.0.2+3
  djangoflow_openapi: ^0.0.24
  djangoflow_openapi_extensions: ^0.0.3+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^9.1.2
  json_annotation: ^4.8.1
  json_theme: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
