name: djangoflow_remote_config
description: Djangoflow Remote Config is a library that helps to handle remote config in your flutter application.
version: 0.1.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_remote_config

environment:
  sdk: ">=3.1.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.3
  djangoflow_bloc_extensions: ^0.1.0
  djangoflow_openapi: ^0.1.22
  djangoflow_openapi_extensions: ^0.0.3+4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.9.0
  json_theme: ^6.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
