name: djangoflow_facebook_analytics
description: A library provides an easy and organized way to implement Facebook Analytics for your Flutter apps.
version: 0.0.1
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analytics: ^1.0.2
  djangoflow_analytics: ^0.0.1
  facebook_app_events: ^0.18.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
