name: djangoflow_facebook_analytics
description: A library provides an easy and organized way to implement Facebook Analytics for your Flutter apps.
version: 0.0.4+2
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_analytics/djangoflow_facebook_analytics

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  analytics: ^1.0.2
  djangoflow_analytics: ^0.0.2+2
  facebook_app_events: ^0.19.0
  flutter:
    sdk: flutter
  mockito: ^5.3.2

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
