name: djangoflow_odoo_auth
description: "Odoo Authentication package for Flutter"
version: 0.1.0
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_odoo/authentication/djangoflow_odoo_auth

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  hydrated_bloc: ^9.1.5
  odoo_rpc: ^0.5.7
  xml_rpc: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
