name: djangoflow_auth_discord
description: djangoflow_auth_discord brings the power of Discord authentication to your Flutter app!
version: 0.1.0+6
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_auth/djangoflow_auth_discord

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  djangoflow_auth: ^0.5.0+1
  flutter:
    sdk: flutter
  http: ^1.1.0
  oauth2_client: ^3.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
