name: djangoflow_auth_discord
description: djangoflow_auth_discord brings the power of Discord authentication to your Flutter app!
version: 0.1.0
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  djangoflow_auth: ^0.3.0+2
  oauth2_client: ^3.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  mockito: ^5.4.2

flutter:
