name: djangoflow_video_player
description: "A Flutter package that provides a highly customizable `VideoPlayerWidget`, making video playback in your Flutter applications seamless and flexible."
version: 0.0.2
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_video_player

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  video_player: ^2.8.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
