name: df_app
description: Djangoflow app with firebase support.
version: 0.0.1
homepage: https://github.com/djangoflow/flutter-djangoflow/packages/df_app

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  freezed_annotation: ^2.1.0
  hydrated_bloc: ^8.1.0
  json_annotation: ^4.6.0
  auto_route: ^4.2.1
  firebase_analytics: ^9.1.12
  firebase_core: ^1.19.1
  firebase_messaging: ^11.4.4
  facebook_app_events: ^0.16.0
  mixpanel_flutter: ^1.5.1
  app_tracking_transparency: ^2.0.2+4
  sentry_flutter: ^6.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  json_serializable:  ^6.3.1
