name: djangoflow_firebase_analytics
description: A library provides an easy and organized way to implement Firebase Analytics for your Flutter apps.
version: 0.2.0
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analytics: ^1.0.2
  djangoflow_analytics: ^0.0.2
  firebase_analytics: ^10.4.3
  firebase_analytics_platform_interface: ^3.6.3
  firebase_core: ^2.14.0
  mockito: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0

flutter:
