name: djangoflow_firebase_analytics
description: A library provides an easy and organized way to implement Firebase Analytics for your Flutter apps.
version: 0.2.0+3
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  analytics: ^1.0.02
  djangoflow_analytics: ^0.0.2+3
  firebase_analytics: ^11.2.1
  firebase_analytics_platform_interface: ^4.2.1
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  mockito: ^5.4.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
