name: djangoflow_mixpanel_analytics
description: A library provides an easy and organized way to implement Mixpanel Analytics for your Flutter apps.
version: 0.1.0+3
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_analytics/djangoflow_mixpanel_analytics

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  analytics: ^1.0.2
  djangoflow_analytics: ^0.0.2+3
  flutter:
    sdk: flutter
  mixpanel_flutter: ^2.2.0
  mockito: ^5.3.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
