name: djangoflow_mixpanel_analytics
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analytics: ^1.0.2
  djangoflow_analytics:
    path: "/Users/saifulislam/Development/apexlabs/djangoflow/flutter-djangoflow/packages/djangoflow_analytics/djangoflow_analytics"
  mixpanel_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
