name: djangoflow_mixpanel_analytics
description: A library provides an easy and organized way to implement Mixpanel Analytics for your Flutter apps.
version: 0.1.0
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analytics: ^1.0.2
  djangoflow_analytics: ^0.0.2
  mixpanel_flutter: ^2.1.1
  mockito: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.0.0

flutter:
