name: djangoflow_auth
description: djangoflow_auth is your ultimate Flutter authentication companion, packed with Djangoflow API supports.
version: 0.3.0+4
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.2
  collection: ^1.18.0
  dio: ^5.3.4
  djangoflow_openapi: ^0.0.24
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^9.1.2
  universal_html: ^2.2.4
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1

flutter:
