name: djangoflow_auth
description: djangoflow_auth is your ultimate Flutter authentication companion, packed with Djangoflow API supports.
version: 0.5.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_auth/djangoflow_auth

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  collection: ^1.18.0
  dio: ^5.5.0+1
  djangoflow_openapi: ^0.1.22
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  hydrated_bloc: ^9.1.5
  universal_html: ^2.2.4
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
