name: djangoflow_deep_link_interface
description: A Djangoflow Flutter package to provide abstraction for deep-link extraction.
version: 1.2.2
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_deep_link/djangoflow_deep_link_interface

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc_test: ^9.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  mockito: ^5.3.2

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
