name: djangoflow_deep_link_interface
description: A Djangoflow Flutter package to provide abstraction for deep-link extraction.
version: 1.2.4
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_deep_link/djangoflow_deep_link_interface

environment:
  sdk: ">=2.18.6 <4.0.0"

dependencies:
  bloc_test: ^9.1.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  mockito: ^5.4.4

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
