name: djangoflow_deep_link_interface
description: A Djangoflow Flutter package to provide abstraction for deep-link extraction.
version: 2.0.0
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_deep_link/djangoflow_deep_link_interface

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  bloc_test: ^9.1.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  mockito: ^5.4.4

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
