name: djangoflow_app_links
description: A Djangoflow package that implements deep-link handling via app_links package.
version: 3.0.1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_deep_link/djangoflow_app_links

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  app_links: ^6.3.2
  bloc_test: ^9.1.7
  djangoflow_deep_link_interface: ^2.0.1
  flutter_bloc: ^8.1.6
  mockito: ^5.4.4

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
