name: djangoflow_app_links
description: A Djangoflow package that implements deep-link handling via app_links package.
version: 1.2.3
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_deep_link/djangoflow_app_links

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  app_links: ^3.4.3
  bloc_test: ^9.1.4
  djangoflow_deep_link_interface: ^1.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  mockito: ^5.3.2

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
