name: djangoflow_app_links
description: A Djangoflow package that implements deep-link handling via app_links package.
version: 1.0.0
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  app_links: ^3.4.1
  djangoflow_deep_link_interface: ^1.0.1
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
