name: djangoflow_app_links
description: A Djangoflow package that implements deep-link handling via app_links package.
version: 1.2.1
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  app_links: ^3.4.3
  bloc_test: ^9.1.4
  djangoflow_deep_link_interface: ^1.2.0
  flutter_bloc: ^8.1.3
  mockito: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.0.0

flutter:
