name: djangoflow_sentry_reporter
description: A library that allows you to report errors to `Sentry` using the `djangoflow_error_reporter` pacakge.
version: 0.1.0+3
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_error_reporters/djangoflow_sentry_reporter

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  djangoflow_error_reporter: ^0.1.0+3
  flutter:
    sdk: flutter
  sentry_flutter: ^7.7.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
