name: djangoflow_sentry_reporter
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  djangoflow_error_reporter: ^0.0.1
  sentry_flutter: ^6.18.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
