name: djangoflow_sentry_reporter
description: A library that allows you to report errors to `Sentry` using the `djangoflow_error_reporter` pacakge.
version: 0.1.0
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  djangoflow_error_reporter: ^0.1.0
  sentry_flutter: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
