# Changes here will be overwritten by Copier
_commit: 2.2.5
_src_path: gh:djangoflow/copier-flutter-project
app_description: A flutter application demonstrating integration of djangoflow_chat
    and [https://github.com/djangoflow/django-df-chat](django-df-chat)
app_label: Djangoflow Chat
app_name: chat
apple_itc_team_id: null
apple_team_id: null
deep_link_host_prod: chat.djangoflow.com
deep_link_host_sandbox: chat.djangoflow.dev
enable_apple_sign_in: false
enable_facebook_sign_in: false
enable_google_sign_in: false
facebook_app_id: null
facebook_client_token: null
firebase_project_id: null
openapi_prod_base_url: https://api.djangoflow.com
openapi_sandbox_base_url: http://127.0.0.1:8000
organization: com.djangoflow.chat
package_name: com.djangoflow.chat.dfchat
project_description: DFChat demonstrates quick integration of chat functionality using
    [https://github.com/djangoflow/django-df-chat](django-df-chat)
project_name: dfchat-flutter
