name: djangoflow_fcm
description: A Djangoflow Flutter project to handle notifications using firebase_messaging
version: 0.1.0+9
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_push_notification/djangoflow_fcm

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc_test: ^9.1.3
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  firebase_messaging_platform_interface: ^4.5.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mockito: ^5.4.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
