name: djangoflow_fcm
description: A Djangoflow Flutter project to handle notifications using firebase_messaging
version: 0.2.0
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_push_notification/djangoflow_fcm

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc_test: ^9.1.3
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_messaging_platform_interface: ^4.5.42
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mockito: ^5.4.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.11
  json_serializable: ^6.8.0
