name: djangoflow_fcm
description: A Djangoflow Flutter project to handle notifications using firebase_messaging
version: 0.1.0
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc_test: ^9.1.3
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  firebase_messaging_platform_interface: ^4.5.3
  json_annotation: ^4.8.1
  mockito: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
