name: djangoflow_auth_apple
description: djangoflow_auth_apple lets you embrace the magic of Apple Sign-In within your Flutter app!
version: 0.1.0+3
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_auth/djangoflow_auth_apple

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  djangoflow_auth: ^0.3.0+5
  flutter:
    sdk: flutter
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
