name: Build djangoflow_openapi using build-runner
run-name: Building djangoflow_openapi using build-runner

on:
  push:
    branches:
      - main
    paths:
      - "packages/djangoflow_openapi/pubspec.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: read-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
        with:
          file-path: packages/djangoflow_openapi/pubspec.yaml
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
        working-directory: packages/djangoflow_openapi/
      - run: dart pub run build_runner build --delete-conflicting-outputs
        working-directory: packages/djangoflow_openapi/
      - name: Commit generated code and create tag
        run: |
          git config --global user.email "saiful@apexive.com"
          git config --global user.name "adar2378"
          git add .
          git commit --allow-empty -m "generate OpenAPI Client code"
          git push origin main
          git tag djangoflow_openapi-${{steps.read-version.outputs.version-number}}
          git push origin djangoflow_openapi-${{steps.read-version.outputs.version-number}}
  # will remove later when secrets with PAT updated
  publish:
    permissions:
      id-token: write # This is required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
        working-directory: packages/djangoflow_openapi/
      - run: dart pub run build_runner build --delete-conflicting-outputs
        working-directory: packages/djangoflow_openapi/
      - name: Publish
        run: dart pub publish --force
        working-directory: packages/djangoflow_openapi/
